### ISSUE TITLE
Pi Hole did not started automatically

### ISSUE THREAD

**Issue by usmanyousaf** [froggtech/scripts#1]
Hello there,
I am running the script Unifi_Pihole on raspberry. Ater successful installation of Unifi Controller, it just stopped at Author, Email & Website. Wondering as per the video, it should run Pi Hole afterwards but did not happen.

**Comment by froggtech** [comment]
Because you let Unifi destroy the script before running PiHole. I removed that part of the script now. You should be good to start with a fresh install of Raspbian and try again.
